# 基本形式

In [23]:
# -*- coding: utf-8 -*-

trainint_set = [[(3,3),1],[(4,3),1],[(1,1),-1]]       
w = [0,0]          
b = 0             

def update(item):
    global w,b
    w[0] += 1*item[1]*item[0][0]              
    w[1] += 1*item[1]*item[0][1]              
    b += 1*item[1]
    print ('w = ',w,'b=',b)                    

def judge(item):                               
    res = 0
    for i in range(len(item[0])):
        res +=item[0][i]*w[i]                   
    res += b                                   
    res *= item[1]                             
    return res

def check():
    flag = False
    for item in trainingSet:
        if judge(item)<=0:
            flag = True
            update(item)
    return flag             #flag=False,说明没有错分的了
        
if __name__ == '__main__':
    flag = False
    for i in range(1000):
        if not check():
            flag = True
            break
    if flag:
        print("分对了")
    else:
        print("还是有错分的")
            

w =  [3, 3] b= 1
w =  [2, 2] b= 0
w =  [1, 1] b= -1
w =  [0, 0] b= -2
w =  [3, 3] b= -1
w =  [2, 2] b= -2
w =  [1, 1] b= -3
分对了


# 对偶形式

In [26]:
import numpy as np

# An example in that book, the training set and parameters' sizes are fixed
training_set = np.array([[[3, 3], 1], [[4, 3], 1], [[1, 1], -1]])

a = np.zeros(len(training_set), np.float)
b = 0.0
Gram = None
y = np.array(training_set[:, 1])
x = np.empty((len(training_set), 2), np.float)
for i in range(len(training_set)):
    x[i] = training_set[i][0]

def cal_gram():
    """
    calculate the Gram matrix
    :return:
    """
    g = np.empty((len(training_set), len(training_set)), np.int)
    for i in range(len(training_set)):
        for j in range(len(training_set)):
            g[i][j] = np.dot(training_set[i][0], training_set[j][0])
    return g


def update(i):
    """
    update parameters using stochastic gradient descent
    :param i:
    :return:
    """
    global a, b
    a[i] += 1
    b = b + y[i]
    print (a,b)

# calculate the judge condition
def cal(i):
    global a, b, x, y

    res = np.dot(a * y, Gram[i])
    res = (res + b) * y[i]
    return res

# check if the hyperplane can classify the examples correctly
def check():
    global a, b, x, y
    flag = False
    for i in range(len(training_set)):
        if cal(i) <= 0:
            flag = True
            update(i)
    if not flag:
        w = np.dot(a * y, x)
        print ("RESULT: w: " + str(w) + " b: " + str(b))
        return False
    return True


if __name__ == "__main__":
    Gram = cal_gram()  # initialize the Gram matrix
    for i in range(1000):
        if not check(): break

[ 1.  0.  0.] 1.0
[ 1.  0.  1.] 0.0
[ 1.  0.  2.] -1.0
[ 1.  0.  3.] -2.0
[ 2.  0.  3.] -1.0
[ 2.  0.  4.] -2.0
[ 2.  0.  5.] -3.0
RESULT: w: [1.0 1.0] b: -3.0
